services:
  - type: web
    name: forjador-backend
    env: python
    plan: free
    buildCommand: cd backend && pip install -r requirements.txt
    startCommand: cd backend && python generate_story.py
    envVars:
      - key: GEMINI_API_KEY
        sync: false 